Fix the "git describe" issue when triggered on annotated tag
When we push a signed and annotated tag to GitHub, this action
will be triggered. Using the default checkout action will
only provide a checkout where HEAD is on an unannotated tag,
even if you add `fetch-depth: 0` and `fetch-tags: true`.
That means that `git describe`, without --tags, will fail
to find the current tag being built, or it will show the
previous annotated tag.

If you run `git describe --tags`, the current tag will be
shown correctly, but I don't want to modify the forked
project's build script for an issue that appears to be with
GitHub's checkout action.

Forcing the checkout ref to be github.ref, seems to resolve
the aforementioned issue for tags, but could be racey, so lets
limit the usage of this to only building for tags.

Checkout https://github.com/actions/checkout/issues/649 for more
context.

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -28,14 +28,21 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-        # Unfortunately, we need tags for git describe to function properly,
-        # which means we will probably need all revision history.
-        #
-        # You must push the upstream linux tags to this github repo for
-        # git describe to work.
+        if: github.ref_type != 'tag'
         with:
           fetch-depth: 0
           fetch-tags: true
+
+      - name: Checkout repository for tag
+        uses: actions/checkout@v4
+        if: github.ref_type == 'tag'
+        # Unfortunately, `git describe` will not function correctly if this
+        # action is triggered by an annotated tag, unless we force it to fetch
+        # ${{ github.ref }}.
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+          ref: ${{ github.ref }}
 
       - name: Install Ubuntu dependencies
         run: |
@@ -50,6 +57,15 @@ jobs:
 
       - name: Install Python dependencies
         run: pip install -r requirements.txt
+
+      # Show git describe, since GitHub has an issue with annotated tags.
+      # When the issue is not mitigated, the following two git describes will
+      # show different tags. Normal `git describe` will show nothing or an old
+      # tag, where `git describe --tags` will show the latest/correct tag.
+      - name: Show git describe
+        run: git describe || echo "'git describe' failed"
+      - name: Show git describe --tags
+        run: git describe --tags || echo "'git describe --tags' failed"
 
       - name: Build Debian package
         run: make deb
